#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SITE_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
ENV_FILE="$SITE_ROOT/.env"
SECRETS_DIR="$SITE_ROOT/.secrets"
CLIENT_FILE="$SECRETS_DIR/blogger-client.json"
TOKEN_FILE="$SECRETS_DIR/blogger-token.json"

native_path() {
  if command -v cygpath >/dev/null 2>&1; then cygpath -w "$1"; else printf '%s' "$1"; fi
}

cd "$SITE_ROOT"

banner "Blogger production setup"

stage "Create the public Blogger site"
say "Create the AdSense-compatible host site and record its public identifiers."
BLOGGER_BLOG_URL=$(_existing BLOGGER_BLOG_URL || true)
BLOGGER_BLOG_ID=$(_existing BLOGGER_BLOG_ID || true)
if [[ "$BLOGGER_BLOG_URL" =~ ^https://[a-zA-Z0-9-]+\.blogspot\.com/?$ && "$BLOGGER_BLOG_ID" =~ ^[0-9]+$ ]]; then
  say "Using the saved Blogger site: $BLOGGER_BLOG_URL"
else
  open_url "https://www.blogger.com/"
  step "Sign in with the Google account that will own the site and receive AdSense payments."
  step "Open the blog selector, select 'New blog', and use the title 'Creature Field Notes'."
  step "Choose an available blogspot.com address. Keep the blog public."
  step "In Theme, choose a responsive theme such as Contempo."
  step "In Settings, turn on 'Visible to search engines' and set the blog language to English."
  ask BLOGGER_BLOG_URL "Paste the full blog URL, including https://:"
  step "Select the blog. Copy the number at the end of the Blogger dashboard URL."
  ask BLOGGER_BLOG_ID "Paste the numeric Blog ID:"
  if [[ ! "$BLOGGER_BLOG_URL" =~ ^https://[a-zA-Z0-9-]+\.blogspot\.com/?$ ]]; then
    warn "The URL is not a standard blogspot.com address."
    exit 1
  fi
  if [[ ! "$BLOGGER_BLOG_ID" =~ ^[0-9]+$ ]]; then
    warn "The Blog ID must contain digits only."
    exit 1
  fi
  write_env BLOGGER_BLOG_URL "$BLOGGER_BLOG_URL"
  write_env BLOGGER_BLOG_ID "$BLOGGER_BLOG_ID"
fi

stage "Create the Blogger OAuth client"
say "Create one Google Cloud project for this local publisher."
open_url "https://console.cloud.google.com/projectcreate"
step "Create a project named 'Creature Field Notes Publisher'."
pause "Press Enter after the project is active."
open_url "https://console.cloud.google.com/apis/library/blogger.googleapis.com"
step "Select the new project and enable Blogger API v3."
pause "Press Enter after the API is enabled."
open_url "https://console.cloud.google.com/auth/branding"
step "Configure Google Auth Platform. Use the same Google account as the support email."
step "Set Audience to External. Add only the Blogger scope: https://www.googleapis.com/auth/blogger"
step "Set the publishing status to In production. Testing tokens expire after seven days."
pause "Press Enter after the app status is In production."
open_url "https://console.cloud.google.com/auth/clients"
step "Create an OAuth client. Select 'Desktop app' and name it 'Local Blogger Publisher'."
step "Download the client JSON file. Google shows its secret only in this file."
ask BLOGGER_CLIENT_DOWNLOAD "Paste the downloaded JSON file's full path:"
mkdir -p "$SECRETS_DIR"
python -c 'import shutil,sys; shutil.copyfile(sys.argv[1], sys.argv[2])' "$BLOGGER_CLIENT_DOWNLOAD" "$(native_path "$CLIENT_FILE")"
write_env BLOGGER_CLIENT_SECRET_FILE "$(native_path "$CLIENT_FILE")"
write_env BLOGGER_TOKEN_FILE "$(native_path "$TOKEN_FILE")"

stage "Authorize the local publisher"
say "The local app requests only the Blogger scope. It never receives your Google password."
if [[ ! -x "$SITE_ROOT/.venv/Scripts/python.exe" ]]; then
  python -m venv "$SITE_ROOT/.venv"
fi
VENV_PYTHON="$SITE_ROOT/.venv/Scripts/python.exe"
"$VENV_PYTHON" -m pip install --disable-pip-version-check -r "$SITE_ROOT/requirements-blogger.txt"
step "A Google consent page will open. Select the Google account that owns the Blogger site."
step "If Google shows an unverified-app warning, continue only if the app name and project are yours."
step "Approve the Blogger access request. The local callback closes the authorization flow."
"$VENV_PYTHON" "$SITE_ROOT/tools/blogger_auth.py"

stage "Add policy pages and enable publishing"
say "Blogger does not expose static-page creation in Blogger API v3, so add these pages once."
open_url "https://www.blogger.com/blog/pages/$BLOGGER_BLOG_ID"
for page in about privacy editorial-policy; do
  case "$page" in
    about) title="About" ;;
    privacy) title="Privacy" ;;
    editorial-policy) title="Editorial Policy" ;;
  esac
  if command -v clip.exe >/dev/null 2>&1; then
    clip.exe < "$SITE_ROOT/blogger/pages/$page.html"
    step "Select 'New page', set the title to '$title', switch to HTML view, and paste."
    pause "Publish '$title', then press Enter. Its HTML is in the clipboard."
  else
    step "Create '$title' from blogger/pages/$page.html and publish it."
    pause "Press Enter after '$title' is public."
  fi
done
step "In Layout, add the Pages gadget and show About, Privacy, and Editorial Policy."
pause "Press Enter after all three links appear on the public site."
"$VENV_PYTHON" "$SITE_ROOT/tools/blogger_publish.py" --source "$(native_path "$SITE_ROOT/../Agent-serial")" --dry-run
confirm "Register the 15-minute approved-episode publisher now?" && \
  powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(native_path "$SITE_ROOT/../Agent/scripts/register-site-publisher-task.ps1")" -IntervalMinutes 15
open_url "$BLOGGER_BLOG_URL"
say "The site is ready for approved episodes. AdSense remains off until Blogger shows eligibility."

finish
